# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 532c88530cec814c9f64acf5a7da29f40eb907ad58ae77f0f94abc73994a6afacd4420ec2568e22aa3d228bc7ee328ef6ae5325411ddf6bedfb0681370656e6d

test:
  secret_key_base: f8b7007e0c2adc5d63a13d29729f03978db7066e185a83ba0ad4fe6d7ad8aa327668f6cbcf35adb86731641fdfda85878ab77abc16ac28bee85edbbf942295d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
